<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AGLauncher.Updater</AssemblyName>
    <RootNamespace>AGLauncher.Updater</RootNamespace>
    <Version>0.4.6</Version>
  </PropertyGroup>
</Project>
