<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Company>Atenoct Games</Company>
    <Copyright>© 2026 Atenoct Games</Copyright>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AGLauncher</AssemblyName>
    <RootNamespace>AGLauncher</RootNamespace>
    <Version>1.0.0.3</Version>
    <DisplayVersion>1.0</DisplayVersion>
    <AssemblyVersion>1.0.0.3</AssemblyVersion>
    <FileVersion>1.0.0.3</FileVersion>
    <ApplicationIcon>Assets\AGLauncher.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bootstrap.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="fallback-manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Assets\BrandLogo.png" />
    <Resource Include="Assets\CastleSurvival.png" />
    <Resource Include="Assets\AGLauncher.ico" />
  </ItemGroup>
</Project>
